/**
 * shopify.server.js
 *
 * Shopify app authentication entry point.
 * Generated by `shopify app init` / Shopify CLI — this is a stub
 * that shows the expected shape. Replace with the CLI-generated
 * version when scaffolding the actual app.
 *
 * In the real scaffold this file wires up:
 *   - OAuth for app installation
 *   - Session token verification
 *   - The `authenticate.admin(request)` helper used across all routes
 *   - The `authenticate.webhook(request)` helper for Shopify webhooks
 */

import '@shopify/shopify-app-remix/adapters/node';
import {
  AppDistribution,
  DeliveryMethod,
  shopifyApp,
  LATEST_API_VERSION,
} from '@shopify/shopify-app-remix/server';
import { PrismaSessionStorage } from '@shopify/shopify-app-session-storage-prisma';
import { PrismaClient }         from '@prisma/client';

const prisma = new PrismaClient();

const shopify = shopifyApp({
  apiKey:            process.env.SHOPIFY_API_KEY,
  apiSecretKey:      process.env.SHOPIFY_API_SECRET,
  apiVersion:        LATEST_API_VERSION,
  scopes:            process.env.SCOPES?.split(','),
  appUrl:            process.env.SHOPIFY_APP_URL,
  authPathPrefix:    '/auth',
  sessionStorage:    new PrismaSessionStorage(prisma),
  distribution:      AppDistribution.AppStore,

  // Register Shopify webhooks the app needs
  webhooks: {
    ARTICLES_UPDATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl:    '/webhooks/articles-update',
    },
  },

  hooks: {
    afterAuth: async ({ session }) => {
      // Register webhooks after a merchant installs/re-installs the app
      shopify.registerWebhooks({ session });
    },
  },

  future: {
    unstable_newEmbeddedAuthStrategy: true,
  },
});

export default shopify;
export const apiVersion     = LATEST_API_VERSION;
export const addDocumentResponseHeaders = shopify.addDocumentResponseHeaders;
export const authenticate   = shopify.authenticate;
export const unauthenticated = shopify.unauthenticated;
export const login          = shopify.login;
export const registerWebhooks = shopify.registerWebhooks;
export const sessionStorage = shopify.sessionStorage;
